language: csharp
mono: none
dotnet: 3.0.100

sudo: false

before_install:
  - chmod +x build.sh
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel Current
  - export PATH="~/.dotnet:$PATH"
 
script: 
  - ./build.sh
